### ISSUE TITLE
Test failures on GitHub macOS actions

### ISSUE THREAD

**Issue by sayrer** [franziskuskiefer/hpke-rs#17]
See:

https://github.com/ctz/rustls/runs/2522332833

This unwrap is failing on GitHub's macOS CI, but not on my local Mac. The tests pass on Linux and Windows in CI.

https://github.com/grafica/rustls/blob/083073b14cbd2c838b4fcb00100252ed9ff7dbe4/rustls/src/ech_key.rs#L252

**Comment by franziskuskiefer** [comment]
Thanks for the report @sayrer ! I suspect that the issue is that the GH macOS CI machines don't have the necessary CPU instructions to use the evercrypt AES implementation. Can you try to add the `"rust-crypto"` feature? This pulls in the RustCrypto AES implementation as fallback for CPUs that are not supported by evercrypt at this point.

**Comment by sayrer** [comment]
Yep, that was it, thanks.

**Comment by sayrer** [comment]
Here's why, fyi:

https://github.com/ctz/rustls/pull/663#issuecomment-834604981

**Comment by franziskuskiefer** [comment]
Nice! I assumed they were using some old Macs and just enabled the fallback for GH actions but never looked into the actual hardware they are using.
